Dracula theme
jordanisaacs/neovim-flake pull request #34
Opened 2023-04-04 10:28 UTC by MonaMayrhofer

This adds support for https://github.com/Mofiqul/dracula.nvim and https://github.com/dracula/vim that are afaik the two most popular implementations of the [Dracula Theme
](https://draculatheme.com/)

Annoyingly they are different in a few regards and if you are used to one switching to the other is a little hassle - so i propose to support them both.

Mofiqul
![image](https://user-images.githubusercontent.com/43534802/229763320-691a3206-709b-4d94-8dcf-1a7cf3ef4b3b.png)

Official
![image](https://user-images.githubusercontent.com/43534802/229763559-88e0eab4-e22f-4091-97b6-7f4e2b86034a.png)

2023-04-04 23:36 UTC, jordanisaacs commented
Thanks for the PR, lgtm! Can you update the commit messages though to be `Themes: Add XXX`. Also, either in an extra commit or within each one (I don't care), can you add a release doc message. Feel free to link to your github profile. I also wrote a [contributing.md](https://github.com/jordanisaacs/neovim-flake/blob/main/CONTRIBUTING.md) for the future.

2023-04-05 20:27 UTC, MonaMayrhofer commented
Should be tidied up now!

2023-04-05 21:35 UTC, jordanisaacs commented
Thanks! Could you address that one comment about "dracula-nvim" naming and then its good to merge.

2023-04-06 07:25 UTC, MonaMayrhofer commented
Wait err i think i missed something - which comment are you referring to? :eyes:

2023-04-06 14:38 UTC, jordanisaacs commented
Hmm, should be a line comment. https://github.com/jordanisaacs/neovim-flake/pull/34#discussion_r1157867443

2023-04-06 14:48 UTC, jordanisaacs requested changes

2023-04-06 14:48 UTC, jordanisaacs commented on flake.nix
> +    dracula-mofiqul = {
Can this be renamed to `dracula-nvim`, and then add "dracula-nvim" to https://github.com/jordanisaacs/neovim-flake/blob/main/modules/statusline/supported_lualine_themes.nix

2023-04-06 14:49 UTC, MonaMayrhofer commented on flake.nix
> +    dracula-mofiqul = {
Alright!

2023-04-06 14:50 UTC, jordanisaacs commented
Ah I'm sorry. Still trying to figure out github's review UI which is very confusing. Didn't realize I had to not just add a comment but press the submit review in the corner. 🤷

2023-04-06 14:59 UTC, MonaMayrhofer commented on flake.nix
> +    dracula-mofiqul = {
Is lualine supposed to automatically inherit the global theme configuration? cuz currently I have to seperately set `theme.name = "dracula-nvim"` and `statusline.lualine.theme = "dracula-nvim"` for it to work, which seems odd

2023-04-06 15:02 UTC, jordanisaacs commented on flake.nix
> +    dracula-mofiqul = {
Probably should fix that to default to the theme (if available). I can fix that in another commit.

2023-04-06 15:02 UTC, MonaMayrhofer commented on flake.nix
> +    dracula-mofiqul = {
Alright

2023-04-06 15:06 UTC, MonaMayrhofer commented
I'm glad it wasn't just me who was blind :P

2023-04-06 15:08 UTC, merged